version: '3'
services:
  heroes:
    container_name: docker-heroes
    restart: always
    build: ./heroes/
    ports:
      - '3000:8081'
    volumes:
      - $PWD:/usr/src/app/heroes
  threats:
    container_name: docker-threats
    restart: always
    build: ./threats/
    ports:
      - '4000:8082'
    volumes:
      - $PWD:/usr/src/app/threats
  db:
    container_name: docker-mongo-db
    image: mongo
    ports:
      - '27017:27017'
