version: '3'
services:
  heroes:
    container_name: docker-heroes
    restart: always
    build: ./heroes/
    ports:
      - '3000:8081'
  threats:
    container_name: docker-threats
    restart: always
    build: ./threats/
    ports:
      - '4000:8082'
  
